# Omakase Ruby styling for Rails, extended with Basecamp house style
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  rubocop-37signals: rubocop.yml

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
